### ISSUE TITLE
Results of Celery Tasks are not available

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#105] opened 2017-12-18 06:17 UTC
After the celery refactor to `current_app` the results are inaccessible using `celery.result.AsyncResult`

To investigate I added the following code in two places in the file `views/index.py`:
![views/index.py - After Import](https://user-images.githubusercontent.com/383862/34092085-9ccef698-e3e7-11e7-911a-af4f0e7cc360.png)

Output:
```
 * Restarting with stat
<Celery clustermgr.application:0x10f43e0d0>

celery.chain
celery.chord
celery.chunks
clustermgr.tasks.all.send_reminder_email
celery.group
celery.backend_cleanup
celery.map
celery.starmap
celery.chord_unlock
celery.accumulate

Backend:  <celery.backends.redis.RedisBackend object at 0x10f9a5790>
 * Debugger is active!
 * Debugger PIN: 196-863-633
```

![views/index.py - in get_log function](https://user-images.githubusercontent.com/383862/34092115-cec8b5f8-e3e7-11e7-939c-6925e4b741fb.png)

Output:

```
<Celery default:0x111486f90>

celery.group
celery.chain
celery.chord
clustermgr.tasks.cluster.InstallLdapServer
celery.chord_unlock
clustermgr.tasks.cluster.collect_server_details
celery.chunks
clustermgr.tasks.cache.get_cache_methods
clustermgr.tasks.cluster.setup_ldap_replication
clustermgr.tasks.cache.restart_services
clustermgr.tasks.cluster.removeMultiMasterDeployement
clustermgr.tasks.all.send_reminder_email
celery.map
clustermgr.tasks.cluster.installGluuServer
celery.starmap
clustermgr.tasks.cache.configure_cache_cluster
celery.backend_cleanup
clustermgr.tasks.cluster.installNGINX
clustermgr.tasks.cache.install_cache_components
clustermgr.tasks.cluster.remove_provider
celery.accumulate

<celery.backends.base.DisabledBackend object at 0x111a21590>
127.0.0.1 - - [18/Dec/2017 11:17:23] "GET /log/0b0689aa-d16b-4a27-8135-c3b6f2ddfc12 HTTP/1.1" 500 -
```

From this it can be noted that the tasks are being assigned to the `default` celery object returned by the `current_app` variable instead of the `clustermgr.application` celery object. I think it is due to the reason `application.py` has the line
![init_celery](https://user-images.githubusercontent.com/383862/34092301-c544d6f0-e3e8-11e7-836e-f309c6f0e4b9.png)
But the celery object returned by the `init_celery` isn't stored or referenced anywhere. So all the `from celery import current_app` returns the default app.

@iromli That's my understanding. I am not sure how to proceed further.

**Comment by tecoholic** [comment] 2017-12-18 06:35
Adding the traceback of the failure

```
127.0.0.1 - - [18/Dec/2017 11:17:23] "GET /log/0b0689aa-d16b-4a27-8135-c3b6f2ddfc12 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tecoholic/work/cluster-mgr/clustermgr/views/index.py", line 253, in get_log
    if result.state == 'SUCCESS' or result.state == 'FAILED':
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/celery/result.py", line 431, in state
    return self._get_task_meta()['status']
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/celery/result.py", line 370, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/Users/tecoholic/work/cluster-mgr/env/lib/python2.7/site-packages/celery/backends/base.py", line 352, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
```

**Comment by iromli** [comment] 2017-12-18 11:54
Is this in `2.1` branch?

**Comment by iromli** [comment] 2017-12-18 12:39
@mbaser told me that `2.1` has been merged to `master`. I'm testing the code in `master` branch now.

**Comment by iromli** [comment] 2017-12-18 12:44
It's strange, I can't reproduce the same error as yours @tecoholic.

![screenshot from 2017-12-18 19 42 16](https://user-images.githubusercontent.com/231601/34106701-cc08c2ba-e42b-11e7-99e5-cc04643ccb82.png)

**Comment by iromli** [comment] 2017-12-18 16:33
I can reproduce the issue when passing `FLASK_DEBUG=1`  env var which enable Flask reloader. It seems, the celery app is not initialized properly.

@mbaser told me that we may need reloader and debugger while developing, so I reverted the code to support `FLASK_DEBUG`. The code already pushed to `master` branch.

**Comment by iromli** [comment] 2017-12-22 17:05
Tested on latest `master` branch, this issue is no longer exist. Going to close this one. Feel free to re-open if errors are found.

**Closed by iromli** 2017-12-22 17:05 UTC
Labels: bug, High Priority
