### ISSUE TITLE
oxAuth Web keys are being out of sync 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#257] opened 2019-03-29 05:33 UTC
`oxAuthConfWebKeys` from LDAP and `/etc/certs/oxauth-keys.json` ( plus oxauth-keys.jks ) should match. 

When we install Gluu Server with Cluster-Manager, seems like they are going out of sync. 
Adding a screenshot from test server. 

Left side: ingredient of `oxAuthConfWebKeys` from LDAP and right side showing `oxauth-keys.json`. 

![oxAuthWebKeys](https://user-images.githubusercontent.com/7156097/55211513-44b52580-51ba-11e9-945c-ee1889b28152.PNG)

**Comment by mbaser** [comment] 2019-03-29 13:30
@yurem explained "no, we not uses oxauth-keys.json after isntallation", so this is not a bug. closing.

**Closed by mbaser** 2019-03-29 13:30 UTC
Labels: High Priority, bug
